language: node_js

matrix:
  include:
  - os: linux
    node_js: 'v10.0.0'

  - os: linux
    node_js: 'v10.16.2'

  - os: linux
    node_js: 'v12.8.0'

script:
  - npm run clean
  - npm run lint
  - npm run build
  - npm run test
